### ISSUE TITLE
It's doing nothing

### ISSUE THREAD

**Issue by pmioduszewski** [angeligareta/woocommerce-to-google-sheets#2]
Hi for me it's doing nothing when I click syncOrders

**Comment by diplomat17** [comment]
> 
> 
> Hi for me it's doing nothing when I click syncOrders

Hi.
I managed to get this to work.
I first came across a 401 server response. I changed the site name to **https**://vyborgrad.com and it helped.

I also had to change line 117 from
`function removeDuplicates(sheet) { SpreadsheetApp.spreadsheet.sheet`
to
`function removeDuplicates(sheet) { sheet`
